{
 "title": "Inventory: Gardener",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Shoots Grouped by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        status,\n        COUNT(id) AS total\nFROM g_shoot\nGROUP BY status\n"
    }
   ]
  },
  {
   "title": "Number of Shoots",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(id) FROM g_shoot;" }
   ]
  },
  {
   "title": "Shoots Grouped By Cloud Profile",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        s.cloud_profile AS cloud_profile,\n        COUNT(id) AS total\nFROM g_shoot AS s\nGROUP BY s.cloud_profile"
    }
   ]
  },
  {
   "title": "Number of Seeds",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT COUNT(id) FROM g_seed;" }
   ]
  },
  {
   "title": "Seed Grouped by Kubernetes Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        kubernetes_version,\n        COUNT(id)\nFROM g_seed\nGROUP BY kubernetes_version\n"
    }
   ]
  },
  {
   "title": "Shoots Grouped By Seed",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        seed_name AS seed,\n        COUNT(id) AS total\nFROM g_shoot\nGROUP BY seed\n"
    }
   ]
  },
  {
   "title": "Top 10 Projects by Shoot Count",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT\n        s.project_name AS project,\n        p.owner AS owner,\n        COUNT(s.id) AS Total\nFROM g_shoot AS s\nINNER JOIN g_project AS p ON s.project_name = p.name\nGROUP BY s.project_name, p.owner\nORDER BY total DESC\nLIMIT 10;"
    }
   ]
  },
  {
   "title": "Machines Grouped by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        status,\n        COUNT(id) AS total\nFROM g_machine\nGROUP BY status\n"
    }
   ]
  },
  {
   "title": "Number of Machines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM g_machine;"
    }
   ]
  },
  {
   "title": "Number of Machines Per Shoot",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT\n        namespace,\n        COUNT(id) as total\nFROM g_machine\nGROUP BY namespace\n"
    }
   ]
  },
  {
   "title": "Backup Buckets by Provider",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        provider_type,\n        COUNT(id) AS total\nFROM g_backup_bucket\nGROUP BY provider_type\n"
    }
   ]
  },
  {
   "title": "Backup Buckets by Region & Provider",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 6, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        provider_type,\n        region_name,\n        COUNT(id) AS total\nFROM g_backup_bucket\nGROUP BY (provider_type, region_name)\n"
    }
   ]
  },
  {
   "title": "Backup Buckets by State",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 13, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        state,\n        COUNT(id) AS total\nFROM g_backup_bucket\nGROUP BY (state);\n"
    }
   ]
  },
  {
   "title": "Number of Backup Buckets",
   "type": "stat",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM g_backup_bucket;\n"
    }
   ]
  }
 ]
}