{
 "title": "Inventory: Worker Metrics (AWS tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"aws:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"aws:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"aws:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"aws:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"aws:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Housekeeper",
   "type": "timeseries",
   "description": "Deleted stale records by the housekeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_housekeeper_deleted_records{model_name=~\"aws:model:.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability Zones",
   "type": "timeseries",
   "description": "Number of collected Availability Zones",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_zones[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Regions",
   "type": "timeseries",
   "description": "Number of collected regions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_regions[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "timeseries",
   "description": "Number of collected S3 Buckets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_aws_buckets) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AMIs",
   "type": "timeseries",
   "description": "Number of collected AMI images",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_images[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPCs",
   "type": "timeseries",
   "description": "Number of collected VPCs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_vpcs[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "timeseries",
   "description": "Number of collected subnets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_subnets[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPCs by region",
   "type": "timeseries",
   "description": "Number of collected VPCs by region",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_aws_vpcs) by (account_id, region)",
     "legendFormat": "{{account_id}}:{{region}}"
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "timeseries",
   "description": "Number of collected Load Balancers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_load_balancers[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "description": "Number of collected instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_instances[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ENIs",
   "type": "timeseries",
   "description": "Number of collected Elastic Network Interfaces (ENIs)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_aws_net_interfaces[30m])) by (account_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances by region",
   "type": "timeseries",
   "description": "Number of collected instances by region",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_aws_instances) by (account_id, region)",
     "legendFormat": "{{account_id}}:{{region}}"
    }
   ]
  }
 ]
}