{
 "title": "Inventory: AWS",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "AWS Account",
    "query": "SELECT DISTINCT(account_id) FROM aws_region"
   }
  ]
 },
 "panels": [
  {
   "title": "VPCs Per Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        v.region_name AS region_name,\n        COUNT(v.id) AS total\nFROM aws_vpc AS v\nWHERE account_id IN ($aws_account)\nGROUP BY v.region_name\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of VPCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_vpc\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "AZs per Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n        region_name,\n        COUNT(id) AS total\nFROM aws_az \nWHERE account_id IN ($aws_account)\nGROUP BY region_name ORDER BY total DESC;\n"
    }
   ]
  },
  {
   "title": "Number of AZs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_az\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "EC2 Instances Grouped by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        instance_type,\n        COUNT(id) AS total\nFROM aws_instance\nWHERE account_id IN ($aws_account)\nGROUP BY instance_type ORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of EC2 Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_instance\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "EC2 Instances Per Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n        v.region_name AS region_name,\n        COUNT(i.id) AS instances\nFROM aws_vpc AS v\nINNER JOIN aws_instance AS i ON v.vpc_id = i.vpc_id AND i.account_id = v.account_id\nWHERE i.account_id IN ($aws_account)\nGROUP BY v.region_name\n"
    }
   ]
  },
  {
   "title": "EC2 Instances Grouped by Arch",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        arch,\n        COUNT(id) AS total\nFROM aws_instance\nWHERE account_id IN ($aws_account)\nGROUP BY arch ORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Subnets Per Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n        v.region_name AS region_name,\n        COUNT(s.id) AS subnets\nFROM aws_vpc AS v\nINNER JOIN aws_subnet AS s ON v.vpc_id = s.vpc_id AND v.account_id = s.account_id\nWHERE s.account_id IN ($aws_account)\nGROUP BY v.region_name"
    }
   ]
  },
  {
   "title": "Number of AWS Subnets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_subnet\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "Buckets Per Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n        b.region_name AS region_name,\n        COUNT(b.id) AS buckets\nFROM aws_bucket AS b\nWHERE b.account_id IN ($aws_account)\nGROUP BY region_name\n"
    }
   ]
  },
  {
   "title": "Number of AWS Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_bucket\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "AMI Images Grouped by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        region_name,\n        COUNT(id) AS total\nFROM aws_image\nWHERE account_id IN ($aws_account)\nGROUP BY region_name"
    }
   ]
  },
  {
   "title": "Number of AWS AMIs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_image\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "AWS Load Balancers by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        type,\n        COUNT(id) AS total\nFROM aws_loadbalancer\nWHERE account_id IN ($aws_account)\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "Number of AWS ELBs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_loadbalancer\nWHERE account_id IN ($aws_account);"
    }
   ]
  },
  {
   "title": "AWS Load Balancers By Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n        region_name,\n        COUNT(id) AS total\nFROM aws_loadbalancer\nWHERE account_id IN ($aws_account)\nGROUP BY region_name;"
    }
   ]
  },
  {
   "title": "AWS Network Interfaces by Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "rawSql": "SELECT\n        region_name,\n        COUNT(id) AS total\nFROM aws_net_interface\nWHERE account_id IN ($aws_account)\nGROUP BY region_name\nORDER BY total DESC"
    }
   ]
  },
  {
   "title": "AWS Network Interfaces by Type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        interface_type,\n        COUNT(id) AS total\nFROM aws_net_interface\nWHERE account_id IN ($aws_account)\nGROUP BY interface_type;"
    }
   ]
  },
  {
   "title": "AWS Number of ENIs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_net_interface\nWHERE account_id IN ($aws_account);\n"
    }
   ]
  },
  {
   "title": "AWS Public IPv4 Addresses by Region",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT\n        region_name,\n        COUNT(id) AS total\nFROM aws_net_interface\nWHERE public_ip_address <> '' AND account_id IN ($aws_account)\nGROUP BY region_name\n"
    }
   ]
  },
  {
   "title": "AWS Public IPv4 Addresses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM aws_net_interface\nWHERE public_ip_address <> '' AND account_id IN ($aws_account);\n"
    }
   ]
  }
 ]
}