{
 "title": "Inventory: Worker Metrics (OpenStack tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"openstack:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"openstack:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"openstack:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"openstack:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"openstack:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Housekeeper",
   "type": "timeseries",
   "description": "Deleted stale records by the housekeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_housekeeper_deleted_records{model_name=~\"openstack:model:.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "timeseries",
   "description": "Number of collected servers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_servers[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "timeseries",
   "description": "Number of collected projects",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_projects[30m])) by (project)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "timeseries",
   "description": "Number of collected subnets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_subnets[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Networks",
   "type": "timeseries",
   "description": "Number of collected Networks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_networks[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Floating IPs",
   "type": "timeseries",
   "description": "Number of collected floating ips",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_floating_ips[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LoadBalancers",
   "type": "timeseries",
   "description": "Number of collected loadbalancers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_loadbalancers[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "timeseries",
   "description": "Number of collected pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_pools[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Routers",
   "type": "timeseries",
   "description": "Number of collected routers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_routers[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ports",
   "type": "timeseries",
   "description": "Number of collected ports",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_ports[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "timeseries",
   "description": "Number of collected containers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_containers[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Objects",
   "type": "timeseries",
   "description": "Number of collected objects",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_objects[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Volumes",
   "type": "timeseries",
   "description": "Number of collected volumes",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(sum_over_time(inventory_openstack_volumes[30m])) by (project)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}