{
 "title": "Inventory: GCP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gcp_project",
    "label": "GCP Project",
    "query": "SELECT project_id FROM gcp_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances Per Region",
   "type": "bargauge",
   "description": "GCP Instances per Region",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.region AS region,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.region;"
    }
   ]
  },
  {
   "title": "Instances Per Zone",
   "type": "barchart",
   "description": "GCP Instances per Zone",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n        i.zone AS zone,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.zone"
    }
   ]
  },
  {
   "title": "Instances Per CPU Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.cpu_platform AS cpu_platform,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.cpu_platform"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM gcp_instance WHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Instances by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.status AS status,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.status"
    }
   ]
  },
  {
   "title": "Number of Networks / VPCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM gcp_vpc WHERE project_id IN ($gcp_project);"
    }
   ]
  }
 ]
}