{
 "title": "Inventory: Leaked Azure Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "az_subscription_name",
    "label": "Azure Subscription",
    "query": "SELECT name FROM az_subscription;"
   }
  ]
 },
 "panels": [
  {
   "title": "List of Unknown VM images",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT * FROM az_unknown_image;"
    }
   ]
  },
  {
   "title": "Number of leaked Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(vm.name) AS total\nFROM az_orphan_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name) AND vm.power_state = 'running'"
    }
   ]
  },
  {
   "title": "Number of leaked Virtual Networks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(vpc.name) AS total\nFROM az_orphan_vpc AS vpc\nINNER JOIN az_subscription AS s ON vpc.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Number of leaked Subnets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(subnet.name) AS total\nFROM az_orphan_subnet AS subnet\nINNER JOIN az_subscription AS s ON subnet.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Leaked Virtual Machines",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT vm.* FROM az_orphan_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name) AND vm.power_state = 'running'"
    }
   ]
  },
  {
   "title": "Leaked Virtual Networks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT vpc.* FROM az_orphan_vpc AS vpc\nINNER JOIN az_subscription AS s ON vpc.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Leaked Subnets",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "rawSql": "SELECT subnet.* FROM az_orphan_subnet AS subnet\nINNER JOIN az_subscription AS s ON subnet.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  }
 ]
}