{
 "title": "Inventory: Azure",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "az_subscription_name",
    "label": "Azure Subscription",
    "query": "SELECT name FROM az_subscription;"
   }
  ]
 },
 "panels": [
  {
   "title": "Resource Groups Per Location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        rg.location AS location,\n        COUNT(rg.id) AS total\nFROM az_resource_group AS rg\nINNER JOIN az_subscription AS s ON rg.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY rg.location\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of Resource Groups",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(rg.id) AS total\nFROM az_resource_group AS rg\nINNER JOIN az_subscription AS s ON rg.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Virtual Networks Per Location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        v.location AS location,\n        COUNT(v.id) AS total\nFROM az_vpc AS v\nINNER JOIN az_subscription AS s ON v.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY v.location\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of Virtual Networks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(v.id) AS total\nFROM az_vpc AS v\nINNER JOIN az_subscription AS s ON v.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Number of Subnets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(subnet.id) AS total\nFROM az_subnet AS subnet\nINNER JOIN az_subscription AS s ON subnet.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Virtual Machines By Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.vm_size AS vm_size,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.vm_size\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Number of Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\n"
    }
   ]
  },
  {
   "title": "Virtual Machines By Location",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.location AS location,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.location\n"
    }
   ]
  },
  {
   "title": "Virtual Machines By Power State",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.power_state AS power_state,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.power_state\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Virtual Machines by Resource Group",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.resource_group AS resource_group,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.resource_group\nORDER BY total DESC\n"
    }
   ]
  },
  {
   "title": "Virtual Machines By Hyper V Generation",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.hyper_v_gen AS hyper_v_gen,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.hyper_v_gen\nORDER BY total DESC;"
    }
   ]
  },
  {
   "title": "Virtual Machines by Image",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n        vm.gallery_image_id AS gallery_image_id,\n        COUNT(vm.id) AS total\nFROM az_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY vm.gallery_image_id\nORDER BY total DESC\n"
    }
   ]
  },
  {
   "title": "Public IP Addresses By Resource Group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        pa.resource_group AS resource_group,\n        COUNT(pa.id) AS total\nFROM az_public_address AS pa\nINNER JOIN az_subscription AS s ON pa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY pa.resource_group;"
    }
   ]
  },
  {
   "title": "Number of Public IP addresses",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(pa.id) AS total\nFROM az_public_address AS pa\nINNER JOIN az_subscription AS s ON pa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\n"
    }
   ]
  },
  {
   "title": "Public IP Addresses by Location",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        pa.location AS location,\n        COUNT(pa.id) AS total\nFROM az_public_address AS pa\nINNER JOIN az_subscription AS s ON pa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY pa.location\nORDER BY total DESC\n"
    }
   ]
  },
  {
   "title": "Public Addresses by IP Version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        pa.ip_version AS ip_version,\n        COUNT(pa.id) AS total\nFROM az_public_address AS pa\nINNER JOIN az_subscription AS s ON pa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY pa.ip_version\n"
    }
   ]
  },
  {
   "title": "Load Balancers By Resource Group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        lb.resource_group AS resource_group,\n        COUNT(lb.id) AS total\nFROM az_lb AS lb\nINNER JOIN az_subscription AS s ON lb.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY lb.resource_group;"
    }
   ]
  },
  {
   "title": "Load Balancers by Location",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        lb.location AS location,\n        COUNT(lb.id) AS total\nFROM az_lb AS lb\nINNER JOIN az_subscription AS s ON lb.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\nGROUP BY lb.location\nORDER BY total DESC\n"
    }
   ]
  },
  {
   "title": "Number of Load Balancers",
   "type": "stat",
   "description": "Number of Load Balancers",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(lb.id) AS total\nFROM az_lb AS lb\nINNER JOIN az_subscription AS s ON lb.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)\n"
    }
   ]
  },
  {
   "title": "Blob containers by Resource Group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  b.resource_group as resource_group,\n  COUNT(b.id) as total\nFROM az_blob_container as b\nINNER JOIN az_subscription as s on b.subscription_id = s.subscription_id\nWHERE s.name in ($az_subscription_name)\nGROUP BY b.resource_group;"
    }
   ]
  },
  {
   "title": "List of blob containers (buckets)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT b.name as container, s.name as subscription, b.storage_account, b.public_access, b.deleted, b.created_at, b.updated_at FROM az_blob_container as b\nINNER JOIN az_subscription AS s ON b.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  },
  {
   "title": "Number of blob containers (buckets)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM az_blob_container as b\nINNER JOIN az_subscription AS s ON b.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  },
  {
   "title": "Storage Accounts by Resource Group",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  sa.resource_group as resource_group,\n  COUNT(sa.id) as total\nFROM az_storage_account as sa\nINNER JOIN az_subscription as s on sa.subscription_id = s.subscription_id\nWHERE s.name in ($az_subscription_name)\nGROUP BY sa.resource_group;"
    }
   ]
  },
  {
   "title": "List of Storage Accounts",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 7, "y": 80 },
   "targets": [
    {
     "rawSql": "SELECT sa.name as storage_account_name, sa.resource_group, s.name as subscription, sa.location, sa.creation_time, sa.created_at, sa.updated_at FROM az_storage_account as sa\nINNER JOIN az_subscription AS s ON sa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  },
  {
   "title": "Number of Storage Accounts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 80 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(sa.id) from az_storage_account as sa\nINNER JOIN az_subscription as s on sa.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  }
 ]
}