{
 "title": "Inventory: Leaked GCP Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gcp_project",
    "label": "GCP Project",
    "query": "SELECT project_id FROM gcp_project"
   }
  ]
 },
 "panels": [
  { "title": "Instances", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Leaked Instances",
   "type": "stat",
   "description": "Number of leaked GCP Compute Engine Instances",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(i.name) AS total\nFROM gcp_orphan_instance AS i\nWHERE i.project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Instances with unknown images",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM gcp_unknown_instance_image\nWHERE project_id in ($gcp_project);"
    }
   ]
  },
  {
   "title": "Leaked Instances",
   "type": "table",
   "description": "Leaked GCP Compute Engine Instances",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT i.*\nFROM gcp_orphan_instance AS i\nWHERE i.project_id IN ($gcp_project);\n"
    }
   ]
  },
  {
   "title": "Instances with Unknown Images",
   "type": "table",
   "description": "List of GCP machine images not specified in a GCP Cloud Profile.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT *\nFROM gcp_unknown_instance_image\nWHERE project_id in ($gcp_project);\n"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leaked GCP Disks",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM gcp_orphan_disk\nWHERE project_id in ($gcp_project);"
      }
     ]
    },
    {
     "title": "Leaked GCP Space",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT SUM(size_gb)\nFROM gcp_orphan_disk\nWHERE project_id IN ($gcp_project)\n"
      }
     ]
    },
    {
     "title": "Leaked GCP Disks",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT * FROM gcp_orphan_disk\nWHERE project_id in ($gcp_project);\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leaked GCP Buckets",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT  count(*) FROM gcp_orphan_bucket AS gob\nWHERE project_id IN ($gcp_project);"
      }
     ]
    },
    {
     "title": "Leaked GCP buckets",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT *\nFROM gcp_orphan_bucket as gob\nWHERE project_id in ($gcp_project);"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks & Subnets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked VPCs",
     "type": "stat",
     "description": "Number of leaked GCP Networks / VPCs",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(v.name) AS total\nFROM gcp_vpc AS v\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE s.technical_id is NULL AND project_id IN ($gcp_project);\n"
      }
     ]
    },
    {
     "title": "Number of Leaked Subnets",
     "type": "stat",
     "description": "Number of leaked GCP Subnets",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(name) FROM gcp_orphan_subnet\nWHERE project_id IN ($gcp_project);\n"
      }
     ]
    },
    {
     "title": "Leaked Networks / VPCs",
     "type": "table",
     "description": "Leaked GCP Networks / VPCs",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n        v.name,\n        v.project_id,\n        v.vpc_id,\n        v.description\nFROM gcp_vpc AS v\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE s.technical_id is NULL AND project_id IN ($gcp_project);"
      }
     ]
    },
    {
     "title": "Leaked Subnets",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT * FROM gcp_orphan_subnet WHERE project_id in ($gcp_project);"
      }
     ]
    }
   ]
  },
  {
   "title": "Load Balancers & Public IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "LBs without Frontend",
     "type": "stat",
     "description": "Load Balancers in inconsistent state",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(id)\nFROM gcp_target_pool_without_frontend \nWHERE project_id IN ($gcp_project)\n"
      }
     ]
    },
    {
     "title": "Target Pools with Non-Existing VMs",
     "type": "stat",
     "description": "Load Balancer Target Pools which point to no longer existing GCE Virtual Machines",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(id)\nFROM gcp_orphan_target_pool \nWHERE project_id IN ($gcp_project)\n"
      }
     ]
    },
    {
     "title": "Number of Leaked Public IPs",
     "type": "stat",
     "description": "LB Public IP addresses which point to Target Pools with no longer existing instance members",
     "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(id)\nFROM gcp_orphan_public_address\nWHERE project_id IN ($gcp_project)\n"
      }
     ]
    },
    {
     "title": "Load Balancers without Frontend",
     "type": "table",
     "description": "List of LBs which do not have a frontend (forwarding rule)",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n  id,\n  name,\n  project_id,\n  region\nFROM gcp_target_pool_without_frontend WHERE project_id in ($gcp_project);"
      }
     ]
    },
    {
     "title": "Target Pools with missing GCE Instances",
     "type": "table",
     "description": "List of Target Pools which point to no longer existing GCE Instance (VM)",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT * FROM gcp_orphan_target_pool WHERE project_id in ($gcp_project);"
      }
     ]
    },
    {
     "title": "Forwarding Rules with Public IPs",
     "type": "table",
     "description": "List of Forwarding Rules (LB Frontend) which point to Target Pools with no longer existing GCE Instances",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "rawSql": "SELECT * FROM gcp_orphan_public_address WHERE project_id in ($gcp_project);"
      }
     ]
    }
   ]
  }
 ]
}