{
 "title": "Inventory: Worker Metrics (Gardener tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"g:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"g:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"g:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"g:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"g:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Housekeeper",
   "type": "timeseries",
   "description": "Deleted stale records by the housekeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_housekeeper_deleted_records{model_name=~\"g:model:.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backup Buckets",
   "type": "timeseries",
   "description": "Number of collected backup buckets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_g_backup_buckets)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "timeseries",
   "description": "Number of collected projects",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(inventory_g_projects)", "legendFormat": "count" }
   ]
  },
  {
   "title": "Project Members",
   "type": "timeseries",
   "description": "Number of collected project members",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_g_project_members)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Seeds",
   "type": "timeseries",
   "description": "Number of collected seeds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(inventory_g_seeds)", "legendFormat": "count" }
   ]
  },
  {
   "title": "Shoots",
   "type": "timeseries",
   "description": "Number of collected shoots",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(inventory_g_shoots)", "legendFormat": "count" }
   ]
  },
  {
   "title": "Machines",
   "type": "timeseries",
   "description": "Number of collected machines by seed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_g_machines) by (seed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seed Volumes",
   "type": "timeseries",
   "description": "Number of collected persistent volumes by seeds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_g_seed_volumes) by (seed)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cloud Profiles",
   "type": "timeseries",
   "description": "Number of collected Cloud Profiles",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_g_cloud_profiles)",
     "legendFormat": "count"
    }
   ]
  }
 ]
}