{
 "title": "Inventory: OpenStack",
 "description": "Resources collected from OpenStack",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "openstack_project",
    "label": "OpenStack Project",
    "query": "SELECT name FROM openstack_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Servers",
   "type": "stat",
   "description": "Number of OpenStack servers.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(s.id)\nFROM openstack_server as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name IN ($openstack_project);"
    }
   ]
  },
  {
   "title": "Servers by Status",
   "type": "piechart",
   "description": "OpenStack servers grouped by status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        s.status AS status,\n        COUNT(s.id) AS total\nFROM openstack_server AS s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY s.status;"
    }
   ]
  },
  {
   "title": "Number of Networks",
   "type": "stat",
   "description": "Number of OpenStack Networks, excluding externally managed networks.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(n.id)\nFROM openstack_network as n\nJOIN openstack_project as p\nON n.project_id = p.project_id\nWHERE p.name in ($openstack_project)"
    }
   ]
  },
  {
   "title": "Networks Per Region",
   "type": "piechart",
   "description": "OpenStack networks grouped by region, excluding externally managed networks.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        COUNT(n.id),\n        n.region \nFROM openstack_network as n\nJOIN openstack_project as p\nON n.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY n.region;"
    }
   ]
  },
  {
   "title": "Number of Subnets",
   "type": "stat",
   "description": "Number of OpenStack Subnets, excluding externally managed subnets.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(s.id) FROM openstack_subnet as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Subnets Per Region",
   "type": "piechart",
   "description": "OpenStack subnets grouped by region, excluding externally managed subnets.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        s.region, COUNT(s.id)\nFROM openstack_subnet as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY s.region"
    }
   ]
  },
  {
   "title": "Subnets by Project",
   "type": "piechart",
   "description": "Subnets grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        p.name, \n        COUNT(*) \nFROM openstack_subnet as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Floating IP Addresses",
   "type": "stat",
   "description": "Number of floating IPs",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_floating_ip as ip\nJOIN openstack_project as p\nON ip.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Floating IP Addresses by Region",
   "type": "piechart",
   "description": "Floating IPs grouped by region.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        ip.region, \n        COUNT(floating_ip) \nFROM openstack_floating_ip as ip\nJOIN openstack_project as p\nON ip.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY ip.region;"
    }
   ]
  },
  {
   "title": "Floating IP Addresses by Project",
   "type": "piechart",
   "description": "Floating IPs grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        p.name, \n        COUNT(*) \nFROM openstack_floating_ip as ip\nJOIN openstack_project as p\nON ip.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Load Balancers",
   "type": "stat",
   "description": "Number of OpenStack Load Balancers.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_loadbalancer as lb\nJOIN openstack_project as p\nON lb.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Load Balancers by Region",
   "type": "piechart",
   "description": "OpenStack Load Balancers grouped by region.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        lb.region, COUNT(*)\nFROM openstack_loadbalancer as lb\nJOIN openstack_project as p\nON lb.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY lb.region;"
    }
   ]
  },
  {
   "title": "Load Balancers by Project",
   "type": "piechart",
   "description": "OpenStack Load Balancers grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        p.name, COUNT(*)\nFROM openstack_loadbalancer as lb\nJOIN openstack_project as p\nON lb.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Routers",
   "type": "stat",
   "description": "Number of OpenStack Routers.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_router as r\nJOIN openstack_project as p\nON r.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Routers by Region",
   "type": "piechart",
   "description": "OpenStack Routers grouped by region.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        r.region, COUNT(*)\nFROM openstack_router as r\nJOIN openstack_project as p\nON r.project_id = p.project_id\nWHERE p.name in ($openstack_project)\nGROUP BY r.region;"
    }
   ]
  },
  {
   "title": "Routers by Project",
   "type": "piechart",
   "description": "OpenStack Routers grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        p.name, COUNT(*)\nFROM openstack_router as r\nJOIN openstack_project as p\nON r.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Pools",
   "type": "stat",
   "description": "Number of OpenStack Pools.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_pool as pool\nJOIN openstack_project as p\nON pool.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Pools by Project",
   "type": "piechart",
   "description": "OpenStack Pools grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        p.name, COUNT(*)\nFROM openstack_pool as pool\nJOIN openstack_project as p\nON pool.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Containers",
   "type": "stat",
   "description": "Number of OpenStack Containers.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_container as c\nJOIN openstack_project as p\nON c.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Containers by Project",
   "type": "piechart",
   "description": "OpenStack Containers grouped by project.",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        p.name, COUNT(*)\nFROM openstack_container as c\nJOIN openstack_project as p\nON c.project_id = p.project_id\nGROUP BY p.project_id, p.name;"
    }
   ]
  },
  {
   "title": "Number of Ports",
   "type": "stat",
   "description": "Number of OpenStack Ports.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_port as port\nJOIN openstack_project as p\nON port.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Number of Pool Members",
   "type": "stat",
   "description": "Number of OpenStack Pool Members.",
   "gridPos": { "h": 8, "w": 7, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_pool_member as pm\nJOIN openstack_project as p\nON pm.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  },
  {
   "title": "Number of Volumes",
   "type": "stat",
   "description": "Number of OpenStack Volumes.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 72 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_volume as v\nJOIN openstack_project as p\nON v.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
    }
   ]
  }
 ]
}