{
 "title": "Inventory: Leaked AWS Resources",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "aws_account",
    "label": "AWS Account",
    "query": "SELECT DISTINCT(account_id) FROM aws_region;"
   }
  ]
 },
 "panels": [
  {
   "title": "Leaked Resources Map",
   "type": "geomap",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.region_name AS region,\n        COUNT(i.id) AS total,\n        gd.latitude AS lat,\n        gd.longitude AS lon,\n        gd.city AS city\nFROM aws_orphan_instance AS i\nINNER JOIN aws_geodata AS gd ON i.region_name = gd.region_name\nWHERE i.state = 'running' AND i.account_id IN ($aws_account)\nGROUP BY (i.region_name, gd.city, gd.latitude, gd.longitude);"
    },
    {
     "rawSql": "SELECT\n        v.region_name AS region,\n        COUNT(v.id) AS total,\n        gd.latitude AS lat,\n        gd.longitude AS lon,\n        gd.city AS city\nFROM aws_orphan_vpc AS v\nINNER JOIN aws_geodata AS gd ON v.region_name = gd.region_name\nWHERE v.account_id IN ($aws_account)\nGROUP BY (v.region_name, gd.city, gd.latitude, gd.longitude);"
    },
    {
     "rawSql": "SELECT\n        b.region_name AS region,\n        COUNT(b.id) AS total,\n        gd.latitude AS lat,\n        gd.longitude AS lon,\n        gd.city AS city\nFROM aws_orphan_bucket AS b\nINNER JOIN aws_geodata AS gd ON b.region_name = gd.region_name\nWHERE b.account_id IN ($aws_account)\nGROUP BY (b.region_name, gd.city, gd.latitude, gd.longitude)\n"
    },
    {
     "rawSql": "SELECT DISTINCT\n       i.region_name AS region,\n       COUNT(i.id) AS total,\n       gd.latitude AS lat,\n       gd.longitude AS lon,\n       gd.city AS city\nFROM aws_instance AS i\nINNER JOIN aws_geodata AS gd ON i.region_name = gd.region_name\nINNER JOIN g_machine AS m ON i.name = m.name\nINNER JOIN g_shoot AS s ON m.namespace = s.technical_id\nLEFT JOIN g_cloud_profile_aws_image AS cpaw ON s.cloud_profile = cpaw.cloud_profile_name AND i.image_id = cpaw.ami\nWHERE i.account_id IN ($aws_account) AND cpaw.ami IS NULL\nGROUP BY (i.region_name, gd.city, gd.latitude, gd.longitude)\n"
    },
    {
     "rawSql": "SELECT\n        i.region_name AS region,\n        COUNT(i.name) AS total,\n        gd.latitude AS lat,\n        gd.longitude AS lon,\n        gd.city AS city\nFROM aws_instance AS i\nINNER JOIN aws_geodata AS gd ON i.region_name = gd.region_name\nWHERE i.launch_time < NOW() - INTERVAL '180 days' AND i.account_id IN ($aws_account)\nGROUP BY (i.region_name, gd.city, gd.latitude, gd.longitude);\n"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked EC2 Instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 0, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(i.name) AS total\nFROM aws_instance AS i\nLEFT JOIN g_machine AS m ON i.name = m.name\nWHERE i.state = 'running' AND m.name IS NULL AND account_id IN ($aws_account);"
      }
     ]
    },
    {
     "title": "Long Running Instances",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 4, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(i.name) AS total\nFROM aws_instance AS i\nWHERE launch_time < NOW() - INTERVAL '180 days' AND account_id IN ($aws_account);\n"
      }
     ]
    },
    {
     "title": "Unknown EC2 Instance Images",
     "type": "stat",
     "description": "Unknown images which are not defined in the respective CloudProfile",
     "gridPos": { "h": 8, "w": 6, "x": 9, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(i.id)\nFROM aws_instance AS i\nINNER JOIN g_machine AS m ON i.name = m.name\nINNER JOIN g_shoot AS s ON m.namespace = s.technical_id\nLEFT JOIN g_cloud_profile_aws_image AS cpaw ON s.cloud_profile = cpaw.cloud_profile_name AND i.image_id = cpaw.ami\nWHERE cpaw.ami IS NULL AND i.account_id IN ($aws_account);\n"
      }
     ]
    },
    {
     "title": "Leaked EC2 Instances",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "rawSql": "SELECT\n        i.name AS instance_name,\n        i.instance_id AS instance_id,\n        i.instance_type AS type,\n        i.state AS state,\n        i.account_id AS account_id,\n\n        v.name AS vpc_name,\n        v.vpc_id AS vpc_id,\n        v.region_name AS region,\n\n        s.name AS shoot,\n        s.project_name AS project\nFROM aws_instance AS i\nLEFT JOIN g_machine AS m ON i.name = m.name\nLEFT JOIN aws_vpc AS v ON i.vpc_id = v.vpc_id\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE i.state = 'running' AND m.name IS NULL AND i.account_id IN ($aws_account);"
      }
     ]
    },
    {
     "title": "Long Running EC2 Instances",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "SELECT\n        i.name AS instance_name,\n        i.instance_id AS instance_id,\n        i.instance_type AS type,\n        i.state AS state,\n        i.account_id AS account_id,\n\n        v.name AS vpc_name,\n        v.vpc_id AS vpc_id,\n        v.region_name AS region,\n\n        s.name AS shoot,\n        s.project_name AS project\nFROM aws_instance AS i\nLEFT JOIN g_machine AS m ON i.name = m.name\nLEFT JOIN aws_vpc AS v ON i.vpc_id = v.vpc_id\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE i.launch_time < NOW() - INTERVAL '180 days' AND i.account_id IN ($aws_account);"
      }
     ]
    },
    {
     "title": "List of Unknown EC2 Instance Images",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "rawSql": "SELECT DISTINCT\n       i.*,\n       s.name AS shoot_name,\n       s.project_name AS project_name\nFROM aws_instance AS i\nINNER JOIN g_machine AS m ON i.name = m.name\nINNER JOIN g_shoot AS s ON m.namespace = s.technical_id\nLEFT JOIN g_cloud_profile_aws_image AS cpaw ON s.cloud_profile = cpaw.cloud_profile_name AND i.image_id = cpaw.ami\nWHERE cpaw.ami IS NULL AND i.account_id IN ($aws_account);\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Leaked S3 Buckets",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(b.name)\nFROM aws_bucket AS b\nLEFT JOIN g_backup_bucket AS gbb ON b.name = gbb.name\nWHERE gbb.name IS NULL AND account_id IN ($aws_account);"
      }
     ]
    },
    {
     "title": "List of Leaked S3 Buckets",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "rawSql": "SELECT b.*\nFROM aws_bucket AS b\nLEFT JOIN g_backup_bucket AS gbb ON b.name = gbb.name\nWHERE gbb.name IS NULL AND account_id IN ($aws_account);"
      }
     ]
    }
   ]
  },
  { "title": "VPCs & Subnets", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Number of Leaked AWS VPCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(v.name) AS total\nFROM aws_orphan_vpc AS v\nWHERE v.account_id IN ($aws_account);\n"
    }
   ]
  },
  {
   "title": "Number of Leaked AWS Subnets",
   "type": "stat",
   "description": "Subnets which are part of a leaked VPC",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(*) AS total\nFROM aws_orphan_subnet AS s\nWHERE s.account_id IN ($aws_account);\n"
    }
   ]
  },
  {
   "title": "Leaked AWS VPCs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n        v.*\nFROM aws_vpc AS v\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE s.technical_id is NULL AND account_id IN ($aws_account);\n"
    }
   ]
  },
  {
   "title": "Leaked AWS Subnets",
   "type": "table",
   "description": "Subnets which belong to VPCs that have been identified as leaked",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT\n        s.*\nFROM aws_subnet AS s\nINNER JOIN aws_vpc AS v ON s.vpc_id = v.vpc_id AND s.account_id = v.account_id\nLEFT JOIN g_shoot AS gs ON v.name = gs.technical_id\nWHERE gs.technical_id IS NULL AND s.account_id IN ($aws_account);\n"
    }
   ]
  }
 ]
}