{
 "title": "Inventory: Leaked OpenStack Resources",
 "description": "Leaked OpenStack resources",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked Servers",
     "type": "stat",
     "description": "Number of leaked OpenStack Servers",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(s.id) AS total\nFROM openstack_orphan_server AS s;"
      }
     ]
    },
    {
     "title": "Servers with unknown images",
     "type": "stat",
     "description": "Servers with images that aren't listed in any respective cloud profile.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(*) FROM openstack_server as s\nLEFT JOIN g_cloud_profile_openstack_image as cpoi\nON s.image_id = cpoi.image_id\nWHERE cpoi.id IS NULL;"
      }
     ]
    },
    {
     "title": "Leaked Servers",
     "type": "table",
     "description": "Leaked OpenStack Servers",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT s.*\nFROM openstack_orphan_server AS s;\n"
      }
     ]
    },
    {
     "title": "Servers with Unknown Images",
     "type": "table",
     "description": "List of OpenStack Server images not specified in a Cloud Profile.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT s.*\nFROM openstack_server as s\nLEFT JOIN g_cloud_profile_openstack_image as cpoi\nON s.image_id = cpoi.image_id\nWHERE cpoi.id IS NULL;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks & Subnets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked Networks",
     "type": "stat",
     "description": "Number of leaked OpenStack Networks",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(n.name) AS total\nFROM openstack_orphan_network AS n;\n"
      }
     ]
    },
    {
     "title": "Number of Leaked Subnets",
     "type": "stat",
     "description": "Number of leaked OpenStack Subnets",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(subnet_id) FROM openstack_orphan_subnet;"
      }
     ]
    },
    {
     "title": "Leaked Networks",
     "type": "table",
     "description": "Leaked OpenStack Networks",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n        n.*\nFROM openstack_orphan_network as n;"
      }
     ]
    },
    {
     "title": "Leaked Subnets",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT * FROM openstack_orphan_subnet;"
      }
     ]
    }
   ]
  },
  { "title": "LoadBalancers & Public IPs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Orphaned Load Balancers",
   "type": "stat",
   "description": "OpenStack Load Balancers which are linked to an orphaned network.",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFROM openstack_orphan_loadbalancer;\n"
    }
   ]
  },
  {
   "title": "Number of Leaked Public (Floating) IPs",
   "type": "stat",
   "description": "Public (Floating) IPs which aren't pointing to networks.",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id)\nFROM openstack_orphan_floating_ip;\n"
    }
   ]
  },
  {
   "title": "Orphan Load Balancers",
   "type": "table",
   "description": "List of LBs which are linked to orphaned networks.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT * FROM openstack_orphan_loadbalancer;"
    }
   ]
  },
  {
   "title": "Orphan floating (public) IPs",
   "type": "table",
   "description": "List of IPs which aren't associated with a network.",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT * FROM openstack_orphan_floating_ip;"
    }
   ]
  }
 ]
}