---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: inventory

namespace: default

generatorOptions:
  disableNameSuffixHash: true

resources:
  - statefulset.yaml
  - service.yaml
