CREATE TABLE IF NOT EXISTS "gcp_forwarding_rule" (
    "rule_id" bigint NOT NULL,
    "project_id" varchar NOT NULL,
    "name" varchar NOT NULL,
    "ip_address" inet,
    "ip_protocol" varchar NOT NULL,
    "ip_version" varchar NOT NULL,
    "all_ports" boolean NOT NULL,
    "allow_global_access" boolean NOT NULL,
    "backend_service" varchar,
    "base_forwarding_rule" varchar,
    "creation_timestamp" varchar,
    "description" varchar NOT NULL,
    "load_balancing_scheme" varchar NOT NULL,
    "network" varchar,
    "network_tier" varchar,
    "port_range" varchar,
    "ports" varchar[],
    "region" varchar NOT NULL,
    "service_label" varchar,
    "service_name" varchar,
    "source_ip_ranges" varchar[],
    "subnetwork" varchar,
    "target" varchar,
    "id" bigserial NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "gcp_forwarding_rule_key" UNIQUE ("rule_id", "project_id")
);
