CREATE TABLE IF NOT EXISTS "aws_net_interface" (
    "region_name" varchar NOT NULL,
    "az" varchar NOT NULL,
    "description" varchar NOT NULL,
    "interface_type" varchar NOT NULL,
    "mac_address" varchar NOT NULL,
    "interface_id" varchar NOT NULL,
    "owner_id" varchar NOT NULL,
    "private_dns_name" varchar NOT NULL,
    "private_ip_address" varchar NOT NULL,
    "requester_id" varchar NOT NULL,
    "requester_managed" boolean NOT NULL,
    "src_dst_check" boolean NOT NULL,
    "status" varchar NOT NULL,
    "subnet_id" varchar NOT NULL,
    "vpc_id" varchar NOT NULL,
    "allocation_id" varchar NOT NULL,
    "association_id" varchar NOT NULL,
    "ip_owner_id" varchar NOT NULL,
    "public_dns_name" varchar NOT NULL,
    "public_ip_address" varchar NOT NULL,
    "attachment_id" varchar NOT NULL,
    "delete_on_termination" boolean NOT NULL,
    "device_index" bigint NOT NULL,
    "instance_id" varchar NOT NULL,
    "instance_owner_id" varchar NOT NULL,
    "attachment_status" varchar NOT NULL,
    "id" bigserial NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    UNIQUE ("interface_id")
);
