CREATE TABLE IF NOT EXISTS "gcp_address" (
    "address" varchar NOT NULL,
    "address_type" varchar NOT NULL,
    "is_global" boolean NOT NULL,
    "creation_timestamp" varchar,
    "description" varchar NOT NULL,
    "address_id" bigint NOT NULL,
    "project_id" varchar NOT NULL,
    "region" varchar NOT NULL,
    "ip_version" varchar NOT NULL,
    "ipv6_endpoint_type" varchar NOT NULL,
    "name" varchar NOT NULL,
    "network" varchar NOT NULL,
    "network_tier" varchar NOT NULL,
    "subnetwork" varchar NOT NULL,
    "prefix_length" bigint NOT NULL,
    "purpose" varchar NOT NULL,
    "self_link" varchar NOT NULL,
    "status" varchar NOT NULL,
    "id" bigserial NOT NULL,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY ("id"),
    CONSTRAINT "gcp_address_key" UNIQUE ("address_id", "project_id")
);
