---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: inventory

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: inventory-config
    files:
      - secrets/config.yaml
