{
 "title": "Inventory: Leaked GCP Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gcp_project",
    "label": "GCP Project",
    "query": "SELECT project_id FROM gcp_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Leaked Instances",
   "type": "stat",
   "description": "Number of leaked GCP Compute Engine Instances",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(i.name) AS total\nFROM gcp_instance AS i\nLEFT JOIN g_machine AS m ON i.name = m.name\nWHERE i.status = 'RUNNING' AND m.name IS NULL AND project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Number of Leaked VPCs",
   "type": "stat",
   "description": "Number of leaked GCP Networks / VPCs",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(v.name) AS total\nFROM gcp_vpc AS v\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE s.technical_id is NULL AND project_id IN ($gcp_project);\n"
    }
   ]
  },
  {
   "title": "Leaked Instances",
   "type": "table",
   "description": "Leaked GCP Compute Engine Instances",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n        i.name,\n        i.instance_id,\n        i.project_id,\n        i.region,\n        i.zone,\n        i.status\nFROM gcp_instance AS i\nLEFT JOIN g_machine AS m ON i.name = m.name\nWHERE i.status = 'RUNNING' AND m.name IS NULL AND project_id IN ($gcp_project);\n"
    }
   ]
  },
  {
   "title": "Leaked Networks / VPCs",
   "type": "table",
   "description": "Leaked GCP Networks / VPCs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n        v.name,\n        v.project_id,\n        v.vpc_id,\n        v.description\nFROM gcp_vpc AS v\nLEFT JOIN g_shoot AS s ON v.name = s.technical_id\nWHERE s.technical_id is NULL AND project_id IN ($gcp_project);"
    }
   ]
  }
 ]
}