{
 "title": "Inventory: Worker Metrics (Azure tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"az:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"az:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"az:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"az:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"az:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Housekeeper",
   "type": "timeseries",
   "description": "Deleted stale records by the housekeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_housekeeper_deleted_records{model_name=~\"az:model:.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VPCs",
   "type": "timeseries",
   "description": "Number of collected VPCs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_vpcs) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "timeseries",
   "description": "Number of collected subscriptions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_subscriptions)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "timeseries",
   "description": "Number of collected subnets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_subnets) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load Balancers",
   "type": "timeseries",
   "description": "Number of collected Load Balancers",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_load_balancers) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Blob Containers",
   "type": "timeseries",
   "description": "Number of collected blob containers",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_blob_containers) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Groups",
   "type": "timeseries",
   "description": "Number of collected resource groups",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_resource_groups) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Public IP Addresses",
   "type": "timeseries",
   "description": "Number of collected public IP addresses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_public_addresses) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Accounts",
   "type": "timeseries",
   "description": "Number of collected Storage Accounts",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_storage_accounts) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Virtual Machines",
   "type": "timeseries",
   "description": "Number of collected VMs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_az_vms) by (subscription_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}