{
 "title": "Inventory: OpenStack",
 "description": "Resources collected from OpenStack",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "openstack_project",
    "label": "OpenStack Project",
    "query": "SELECT name FROM openstack_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of Servers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM openstack_server;"
    }
   ]
  },
  {
   "title": "Servers by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        s.status AS status,\n        COUNT(s.id) AS total\nFROM openstack_server AS s\nGROUP BY s.status"
    }
   ]
  },
  {
   "title": "Number of Networks",
   "type": "stat",
   "description": "OpenStack Networks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM openstack_network;"
    }
   ]
  },
  {
   "title": "Networks Per Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        COUNT(n.id),\n        region \nFROM openstack_network as n\nGROUP BY region;"
    }
   ]
  },
  {
   "title": "Number of Subnets",
   "type": "stat",
   "description": "OpenStack Subnets",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM openstack_subnet;"
    }
   ]
  },
  {
   "title": "Subnets Per Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        s.region, COUNT(s.id)\nFROM openstack_subnet as s\nGROUP BY s.region"
    }
   ]
  },
  {
   "title": "Number of Public IP Addresses",
   "type": "stat",
   "description": "Number of public (floating) IP Addresses",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM openstack_floating_ip;"
    }
   ]
  },
  {
   "title": "Public IP Addresses by Region",
   "type": "piechart",
   "description": "Public (floating) IP Adresses grouped by region",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        region, \n        COUNT(floating_ip) \nFROM openstack_floating_ip \nGROUP BY region;"
    }
   ]
  },
  {
   "title": "Number of Load Balancers",
   "type": "stat",
   "description": "OpenStack Load Balancers",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM openstack_loadbalancer;"
    }
   ]
  },
  {
   "title": "Load Balancers by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        region, COUNT(id)\nFROM openstack_loadbalancer\nGROUP BY region;"
    }
   ]
  }
 ]
}