{
 "title": "Inventory: Worker Metrics (ODG tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"odg:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"odg:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"odg:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"odg:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"odg:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Discovered Orphan Resources",
   "type": "timeseries",
   "description": "Number of collected discovered orphan resources from Inventory",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_odg_discovered_orphan_resources) by (resource_kind)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reported Orphan Resources",
   "type": "timeseries",
   "description": "Number of orphan resources reported to the ODG API",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_odg_reported_orphan_resources) by (resource_kind)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}