{
 "title": "Inventory: Worker Metrics (GCP tasks)",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Successful Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been successfully executed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_successful_total{task_name=~\"gcp:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "timeseries",
   "description": "Duration of task execution in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(inventory_task_duration_seconds_sum{task_name=~\"gcp:task:.*\"}[30m])) by (task_name)\n/\nsum(rate(inventory_task_duration_seconds_count{task_name=~\"gcp:task:.*\"}[30m])) by (task_name)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Tasks",
   "type": "timeseries",
   "description": "Number of times a task has failed in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_failed_total{task_name=~\"gcp:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Skipped Tasks",
   "type": "timeseries",
   "description": "Number of times a task has been skipped from being retried in a 30 minute window",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(sum(increase(inventory_task_skipped_total{task_name=~\"gcp:task:.*\"}[30m])) by (task_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Housekeeper",
   "type": "timeseries",
   "description": "Deleted stale records by the housekeeper",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_housekeeper_deleted_records{model_name=~\"gcp:model:.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Buckets",
   "type": "timeseries",
   "description": "Number of collected buckets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_buckets) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Projects",
   "type": "timeseries",
   "description": "Number of collected projects",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "sum(inventory_gcp_projects)", "legendFormat": "count" }
   ]
  },
  {
   "title": "VPCs",
   "type": "timeseries",
   "description": "Number of collected VPCs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_vpcs) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "timeseries",
   "description": "Number of collected disks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_disks) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subnets",
   "type": "timeseries",
   "description": "Number of collected subnets",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_subnets) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Addresses",
   "type": "timeseries",
   "description": "Number of collected global and regional addresses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_addresses) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "description": "Number of collected instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_instances) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GKE Clusters",
   "type": "timeseries",
   "description": "Number of collected GKE Clusters",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_gke_clusters) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Target Pools",
   "type": "timeseries",
   "description": "Number of collected Target Pools",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_target_pools) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forwarding Rules",
   "type": "timeseries",
   "description": "Number of collected Forwarding Rules",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(inventory_gcp_forwarding_rules) by (project_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}