{
 "title": "Inventory: Leaked OpenStack Resources",
 "description": "Leaked OpenStack resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "openstack_project",
    "query": "SELECT name FROM openstack_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Servers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked Servers",
     "type": "stat",
     "description": "Number of leaked OpenStack servers.\nLeaked here means server instances that do not have a matching Machine resource.\n\n",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(s.id) AS total\nFROM openstack_orphan_server AS s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Servers with unknown images",
     "type": "stat",
     "description": "Number of servers using images that aren't listed in their respective cloud profile.\nOnly looks at non-leaked servers.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(oumi.server_id) FROM openstack_unknown_machine_image as oumi\nJOIN openstack_project as p\nON oumi.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Leaked Servers",
     "type": "table",
     "description": "List of leaked OpenStack servers.\nLeaked here means not mapped to a Machine resource.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT s.*\nFROM openstack_orphan_server AS s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project);\n"
      }
     ]
    },
    {
     "title": "Servers with Unknown Images",
     "type": "table",
     "description": "List of OpenStack Server using images not specified in their respective Cloud Profile.\nOnly looks at non-leaked servers.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "rawSql": "SELECT oumi.*\nFROM openstack_unknown_machine_image as oumi\nJOIN openstack_project as p\nON oumi.project_id = p.project_id\nWHERE p.name in ($openstack_project);\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Networks & Subnets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Leaked Networks",
     "type": "stat",
     "description": "Number of leaked OpenStack Networks.\nDoes not include externally managed networks.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n        COUNT(n.name) AS total\nFROM openstack_orphan_network AS n\nJOIN openstack_project as p\nON n.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Number of Leaked Subnets",
     "type": "stat",
     "description": "Number of leaked OpenStack Subnets",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(s.subnet_id) FROM openstack_orphan_subnet as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Leaked Networks",
     "type": "table",
     "description": "Leaked OpenStack Networks.\nDoes not include externally managed networks.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n        n.*\nFROM openstack_orphan_network as n\nJOIN openstack_project as p\nON n.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Leaked Subnets",
     "type": "table",
     "description": "List of leaked OpenStack subnets.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
     "targets": [
      {
       "rawSql": "SELECT s.* as project_name \nFROM openstack_orphan_subnet as s\nJOIN openstack_project as p\nON s.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    }
   ]
  },
  {
   "title": "LoadBalancers & Public IPs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Orphaned Load Balancers",
     "type": "stat",
     "description": "Number of OpenStack Load Balancers which are linked to an orphaned network.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(lb.id)\nFROM openstack_orphan_loadbalancer as lb\nJOIN openstack_project as p\nON lb.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Number of Leaked Public (Floating) IPs",
     "type": "stat",
     "description": "Number of public (floating) IPs which are linked to leaked networks.",
     "gridPos": { "h": 7, "w": 4, "x": 4, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(ip.id)\nFROM openstack_orphan_floating_ip as ip\nJOIN openstack_project as p\nON ip.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Orphan Load Balancers",
     "type": "table",
     "description": "List of LBs which are linked to orphaned networks.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT \n  lb.*,\n  p.name as project_name\nFROM openstack_orphan_loadbalancer as lb\nJOIN openstack_project as p\nON lb.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    },
    {
     "title": "Orphan floating (public) IPs",
     "type": "table",
     "description": "List of IPs which are linked with an orphan network.",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 21 },
     "targets": [
      {
       "rawSql": "SELECT \n  ip.*,\n  p.name as project_name\nFROM openstack_orphan_floating_ip as ip\nJOIN openstack_project as p\nON ip.project_id = p.project_id\nWHERE p.name in ($openstack_project);"
      }
     ]
    }
   ]
  }
 ]
}