{
 "title": "Inventory: Leaked Azure Resources",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "az_subscription_name",
    "label": "Azure Subscription",
    "query": "SELECT name FROM az_subscription;"
   }
  ]
 },
 "panels": [
  {
   "title": "Number of leaked Virtual Machines",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(vm.name) AS total\nFROM az_orphan_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name) AND vm.power_state = 'running'"
    }
   ]
  },
  {
   "title": "Number of leaked Virtual Networks",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(vpc.name) AS total\nFROM az_orphan_vpc AS vpc\nINNER JOIN az_subscription AS s ON vpc.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Number of leaked Subnets",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(subnet.name) AS total\nFROM az_orphan_subnet AS subnet\nINNER JOIN az_subscription AS s ON subnet.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Number of leaked Blob Containers (buckets)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(b.name) AS total\nFROM az_orphan_blob_container AS b\nINNER JOIN az_subscription AS s ON b.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Number of unknown VM images",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*) FROM az_unknown_image as i\nINNER JOIN az_subscription as s on s.subscription_id = i.subscription_id\nWHERE s.name in ($az_subscription_name);"
    }
   ]
  },
  {
   "title": "Leaked Virtual Machines",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT vm.* FROM az_orphan_vm AS vm\nINNER JOIN az_subscription AS s ON vm.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name) AND vm.power_state = 'running'"
    }
   ]
  },
  {
   "title": "Leaked Virtual Networks",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT vpc.* FROM az_orphan_vpc AS vpc\nINNER JOIN az_subscription AS s ON vpc.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "Leaked Subnets",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "rawSql": "SELECT subnet.* FROM az_orphan_subnet AS subnet\nINNER JOIN az_subscription AS s ON subnet.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name)"
    }
   ]
  },
  {
   "title": "List of orphaned blob containers (buckets)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "rawSql": "SELECT \n  b.name as name,\n  b.storage_account,\n  b.resource_group,\n  b.last_modified_time,\n  s.name as subscription\nFROM az_orphan_blob_container as b\nINNER JOIN az_subscription as s on b.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  },
  {
   "title": "List of Unknown VM images",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "rawSql": "SELECT \n  i.gallery_image_id as gallery_image_id,\n  s.name as subscription\nFROM az_unknown_image as i\nINNER JOIN az_subscription as s on i.subscription_id = s.subscription_id\nWHERE s.name IN ($az_subscription_name);"
    }
   ]
  }
 ]
}