{
 "title": "Inventory: GCP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gcp_project",
    "label": "GCP Project",
    "query": "SELECT project_id FROM gcp_project"
   }
  ]
 },
 "panels": [
  {
   "title": "Instances Per Region",
   "type": "piechart",
   "description": "GCP Instances per Region",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.region AS region,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.region;"
    }
   ]
  },
  {
   "title": "Instances Per Zone",
   "type": "barchart",
   "description": "GCP Instances per Zone",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n        i.zone AS zone,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.zone"
    }
   ]
  },
  {
   "title": "Instances Per CPU Platform",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.cpu_platform AS cpu_platform,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.cpu_platform"
    }
   ]
  },
  {
   "title": "Number of Instances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM gcp_instance WHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Instances by Status",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        i.status AS status,\n        COUNT(i.id) AS total\nFROM gcp_instance AS i\nWHERE i.project_id IN ($gcp_project)\nGROUP BY i.status"
    }
   ]
  },
  {
   "title": "Number of Networks / VPCs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM gcp_vpc WHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Public IP Addresses by Region",
   "type": "piechart",
   "description": "External/Public IP Addresses by Region",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        region, \n        COUNT(ip_address) \nFROM gcp_public_address\nWHERE project_id IN ($gcp_project)\nGROUP BY region;\n"
    }
   ]
  },
  {
   "title": "Origin of Public IP Addresses",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n        origin, \n        COUNT(ip_address)\nFROM gcp_public_address\nWHERE project_id IN ($gcp_project)\nGROUP BY origin;"
    }
   ]
  },
  {
   "title": "Number of Public IP Addresses",
   "type": "stat",
   "description": "Number of external/public IP addresses",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM gcp_public_address WHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Subnets Per Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "rawSql": "SELECT\n        s.region,\n        COUNT(s.id)\nFROM gcp_subnet as s\nWHERE s.project_id IN ($gcp_project)\nGROUP BY s.region;"
    }
   ]
  },
  {
   "title": "Number of GCP Subnets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM gcp_subnet\nWHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Buckets Per Region",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT\n        b.location AS region_name,\n        COUNT(b.id) AS buckets\nFROM gcp_bucket AS b\nWHERE b.project_id IN ($gcp_project)\nGROUP BY region_name\n"
    }
   ]
  },
  {
   "title": "Number of GCP Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM gcp_bucket\nWHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "GCP Number of NICs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM gcp_nic\nWHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "Forwarding Rules by Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        region, COUNT(id)\nFROM gcp_forwarding_rule\nWHERE project_id IN ($gcp_project)\nGROUP BY region;"
    }
   ]
  },
  {
   "title": "Forwarding Rules by LB Scheme",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 7, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        load_balancing_scheme, COUNT(id)\nFROM gcp_forwarding_rule\nWHERE project_id IN ($gcp_project)\nGROUP BY load_balancing_scheme;"
    }
   ]
  },
  {
   "title": "Forwarding Rules by IP Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 13, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        ip_protocol, COUNT(id)\nFROM gcp_forwarding_rule\nWHERE project_id IN ($gcp_project)\nGROUP BY ip_protocol;"
    }
   ]
  },
  {
   "title": "Number of Forwarding Rules",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM gcp_forwarding_rule\nWHERE project_id IN ($gcp_project);"
    }
   ]
  },
  {
   "title": "GKE Clusters grouped by location",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        location, COUNT(id)\nFROM gcp_gke_cluster\nWHERE project_id IN ($gcp_project)\nGROUP BY location;"
    }
   ]
  },
  {
   "title": "GKE Clusters grouped by version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        current_master_version, COUNT(id)\nFROM gcp_gke_cluster\nWHERE project_id IN ($gcp_project)\nGROUP BY current_master_version;"
    }
   ]
  },
  {
   "title": "Number of GKE Clusters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM gcp_gke_cluster\nWHERE project_id in ($gcp_project);"
    }
   ]
  },
  {
   "title": "Number of GCP disks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        COUNT(id)\nFROM gcp_disk\nWHERE project_id IN ($gcp_project)\n"
    }
   ]
  },
  {
   "title": "GCP Disks per Region",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        region, COUNT(id)\nFROM gcp_disk\nWHERE project_id IN ($gcp_project)\nGROUP BY region;"
    }
   ]
  },
  {
   "title": "GCP Disks grouped by type",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        type, COUNT(id)\nFROM gcp_disk\nWHERE project_id IN ($gcp_project)\nGROUP BY type;"
    }
   ]
  },
  {
   "title": "GCP Disks grouped by size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        CONCAT(size_gb, 'GB'), COUNT(id)\nFROM gcp_disk\nWHERE project_id IN ($gcp_project)\nGROUP BY CONCAT(size_gb, 'GB')\n"
    }
   ]
  },
  {
   "title": "GCP Disks Total Space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n        SUM(size_gb)\nFROM gcp_disk\nWHERE project_id IN ($gcp_project)\n"
    }
   ]
  }
 ]
}