---
version: v1alpha1
debug: false

redis:
  endpoint: redis:6379

database:
  dsn: "postgresql://inventory:p4ssw0rd@postgres:5432/inventory?sslmode=disable"
  migration_dir: ./internal/pkg/migrations

worker:
  concurrency: 100

dashboard:
  address: ":8080"
  read_only: false
  prometheus_endpoint: http://prometheus:9090/

gcp:
  soil_regional_host:
  soil_regional_ca_path:

# AWS specific configuration
aws:
  region: eu-central-1  # Frankfurt
  default_region: eu-central-1  # Frankfurt
  app_id: gardener-inventory  # Optional application specific identifier

  # This section provides configuration specific to each AWS service and which
  # named credentials are used for each service. This allows the Inventory to
  # connect to multiple AWS accounts based on the named credentials which are
  # used. Inventory will connect to all configured named credentials (accounts)
  # during collection from the respective AWS service.
  services:
    ec2:
      use_credentials:
        - default
        - account-foo
        - account-bar
    elb:
      use_credentials:
        - default
        - account-foo
    elbv2:
      use_credentials:
        - default
    s3:
      use_credentials:
        - default
        - account-bar

  # The `credentials' section provides named credentials, which are used by the
  # various AWS services. The currently supported token retrievers are `none',
  # `kube_sa_token' and `token_file'. See docs/oidc-aws.md for more details.
  credentials:
    default:
      # When using `none' as the token retriever, only the shared AWS
      # credentials file is used.
      token_retriever: none

    account-foo:
      # Example configuration for `kube_sa_token' retriever. When using this
      # token retriever the Inventory will request a Kubernetes Service Account
      # token using the specified kubeconfig, which is then exchanged for
      # temporary security credentials via the AWS STS service.  It is expected
      # that OIDC Trust is already established between Inventory and AWS when
      # using this token retriever.
      token_retriever: kube_sa_token
      kube_sa_token:
        kubeconfig: /path/to/kubeconfig
        namespace: inventory
        service_account: worker
        duration: 30m
        audiences:
          - iaas-aws-dev
        role_arn: arn:aws:iam::account:role/gardener-inventory-dev
        role_session_name: gardener-inventory-worker

    account-bar:
      # Example configuration for `token_file' retriever. When using this token
      # retriever the Inventory will exchange the token contained within the
      # specified file for temporary security credentials via the AWS STS
      # service. It is expected that OIDC Trust is already established between
      # Inventory and AWS when using this token retriever.
      token_retriever: token_file
      token_file:
        path: /path/to/identity/token
        duration: 30m
        role_arn: arn:aws:iam::account:role/name
        role_session_name: gardener-inventory-worker

scheduler:
  jobs:
    # AWS
    - name: "aws:task:collect-regions"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS Regions"
    - name: "aws:task:collect-azs"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS AZs"
    - name: "aws:task:collect-vpcs"
      spec: "@every 1h"
      desc: "Collect AWS VPCs"
    - name: "aws:task:collect-subnets"
      spec: "@every 1h"
      desc: "Collect AWS Subnets"
    - name: "aws:task:collect-instances"
      spec: "@every 1h"
      desc: "Collect AWS EC2 Instances"
    - name: "aws:task:collect-images"
      spec: "@every 1h"
      desc: "Collect AWS AMIs"
      # this ID was taken from the AWS Web UI as the owner of garden-linux images
      payload: >-
        owners:
          - 544319711298
    - name: "aws:task:collect-loadbalancers"
      spec: "@every 24h"
      desc: "Collect AWS LoadBalancers"
    - name: "aws:task:collect-buckets"
      spec: "@every 24h"
      desc: "Collect AWS S3 Buckets"
    - name: "aws:task:collect-net-interfaces"
      spec: "@every 1h"
      desc: "Collect AWS Network Interfaces"
    - name: "aws:task:link-all"
      spec: "@every 30m"
      desc: "Link all AWS models"

    # Gardener
    - name: "g:task:collect-projects"
      spec: "@every 1h"
      desc: "Collect Gardener Projects"
    - name: "g:task:collect-seeds"
      spec: "@every 1h"
      desc: "Collect Gardener Seeds"
    - name: "g:task:collect-shoots"
      spec: "@every 1h"
      desc: "Collect Gardener Shoots"
    - name: "g:task:collect-machines"
      spec: "@every 1h"
      desc: "Collect Gardener Machines"
    - name: "g:task:collect-backup-buckets"
      spec: "@every 1h"
      desc: "Collect Gardener BackupBuckets"
    - name: "g:task:collect-cloud-profiles"
      spec: "@every 1h"
      desc: "Collect Gardener CloudProfiles"
    - name: "g:task:link-all"
      spec: "@every 30m"
      desc: "Link all Gardener models"

    # The housekeeper takes care of cleaning up stale records
    - name: "common:task:housekeeper"
      spec: "@every 12h"
      payload: >-
        retention:
          # AWS
          - name: "aws:model:region"
            duration: 1080h  # 45 days
          - name: "aws:model:az"
            duration: 1080h  # 45 days
          - name: "aws:model:vpc"
            duration: 24h
          - name: "aws:model:subnet"
            duration: 24h
          - name: "aws:model:instance"
            duration: 24h
          - name: "aws:model:image"
            duration: 24h
          - name: "aws:model:bucket"
            duration: 24h
          - name: "aws:model:loadbalancer"
            duration: 24h
          - name: "aws:model:network_interface"
            duration: 24h
          # Gardener
          - name: "g:model:project"
            duration: 24h
          - name: "g:model:seed"
            duration: 168h  # 7 days
          - name: "g:model:shoot"
            duration: 24h
          - name: "g:model:machine"
            duration: 24h
          - name: "g:model:backup_bucket"
            duration: 24h
          - name: "g:model:cloud_profile"
            duration: 24h
          - name: "g:model:cloud_profile_aws_image"
            duration: 24h

virtual_garden:
  # Path to token for Virtual Garden cluster authentication
  token_path:

  # Path to Virtual Garden kubeconfig
  kubeconfig:

  # Environment type (dev, staging, canary, live)
  environment: dev

  # The list of excluded seeds specifies seed cluster names, from which
  # collection will be skipped.
  excluded_seeds:
    - seed-a
    - seed-b
