---
version: v1alpha1
debug: false

redis:
  endpoint: 127.0.0.1:6379

database:
  dsn: "postgresql://inventory:p4ssw0rd@localhost:5432/inventory?sslmode=disable"
  migration_dir: ./internal/pkg/migrations

worker:
  concurrency: 10

scheduler:
  jobs:
    - name: "aws:collect-regions"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS Regions"
    - name: "aws:collect-azs"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS AZs"
    - name: "aws:collect-vpcs"
      spec: "@every 1h"
      desc: "Collect AWS VPCs"
    - name: "aws:collect-subnets"
      spec: "@every 1h"
      desc: "Collect AWS Subnets"
    - name: "aws:collect-instances"
      spec: "@every 1h"
      desc: "Collect AWS EC2 Instances"
