---
version: v1alpha1
debug: false

redis:
  endpoint: 127.0.0.1:6379

database:
  dsn: "postgresql://inventory:p4ssw0rd@localhost:5432/inventory?sslmode=disable"
  migration_dir: ./internal/pkg/migrations

worker:
  concurrency: 10

scheduler:
  jobs:
    - name: "aws:task:collect-regions"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS Regions"
    - name: "aws:task:collect-azs"
      spec: "@every 720h"  # 30 days
      desc: "Collect AWS AZs"
    - name: "aws:task:collect-vpcs"
      spec: "@every 1h"
      desc: "Collect AWS VPCs"
    - name: "aws:task:collect-subnets"
      spec: "@every 1h"
      desc: "Collect AWS Subnets"
    - name: "aws:task:collect-instances"
      spec: "@every 1h"
      desc: "Collect AWS EC2 Instances"

    # The housekeeper takes care of cleaning up stale records
    - name: "common:task:housekeeper"
      spec: "@every 2h"
      payload: >-
        retention:
          # AWS
          - name: "aws:model:region"
            duration: 1080h  # 45 days
          - name: "aws:model:az"
            duration: 1080h  # 45 days
          - name: "aws:model:vpc"
            duration: 4h
          - name: "aws:model:subnet"
            duration: 4h
          - name: "aws:model:instance"
            duration: 4h
          # Gardener
          - name: "g:model:project"
            duration: 24h
          - name: "g:model:seed"
            duration: 168h  # 7 days
          - name: "g:model:shoot"
            duration: 4h
          - name: "g:model:machine"
            duration: 4h

virtual_garden:
  # Path to Virtual Garden kubeconfig
  kubeconfig: