---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: valkey
    app.kubernetes.io/component: valkey
    app.kubernetes.io/part-of: inventory
    app.kubernetes.io/managed-by: kustomize
  name: valkey
spec:
  replicas: 1
  selector:
    matchLabels:
      app: valkey
  serviceName: valkey
  template:
    metadata:
      labels:
        app: valkey
    spec:
      containers:
      - name: valkey
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
        image: valkey/valkey:8.1-alpine
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
              - sh
              - -c
              - "valkey-cli ping"
          initialDelaySeconds: 5
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          exec:
            command:
              - sh
              - -c
              - "valkey-cli ping"
      securityContext:
        fsGroup: 999
        runAsGroup: 999
        runAsUser: 999
