---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 9090
    name: prometheus
  selector:
    app: prometheus
