---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: inventory

namespace: inventory

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - ../redis
  - ../postgres
  - ../grafana
  - ../prometheus
  - ../config
  - ../scheduler
  - ../worker
  - ../dashboard
